# Book settings
# jupyter-book build --all ./


title: Puzzle Schedules
author: Jonathan Alexander, Madalyn Li, Hannah Luebbering, Aishwarya Singh
logo: _static/images/icons/puzzle2.png
exclude_patterns: ["README.md"]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - _static/references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/hluebbering/puzzle-scheduling  # Online location of your book
  # path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: gh-pages  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: false
  use_repository_button: true
  favicon: ""
  use_edit_page_button: false
#  use_multitoc_numbering: true
  extra_navbar: Powered by <a href="https://jupyterbook.org">Hoefnagel Puzzles</a>  # Will be displayed underneath the left navbar.
  extra_footer: ""
  home_page_in_navbar: true

    
launch_buttons:
  notebook_interface: "classic"